"""Crystal Springs Golf Trip — curated playlist data.

Ten playlists for a 4-day golf trip. Four guys, early 40s, drinks,
gambling, Airbnb nights. ~40% rap / 30% country / 20% rock / 10% classic
rock overall preference, explicit versions preferred.

Each song is (artist, title, length "m:ss", genre).
Genres: Rap | Country | Rock | Classic Rock
Reggae-rock (Stick Figure, Sublime, Dirty Heads, O.A.R., 311, etc.) is
tagged Rock.

Hard rules enforced by generate_playlists.py:
  - Zero duplicate songs across ALL playlists (including Trip Anthem).
  - No primary artist more than 3x within a single playlist, unless the
    playlist sets its own "max_artist" (The Ride Up runs Eminem-heavy
    on purpose).
"""

PLAYLISTS = [
    {
        "name": "Minerals",
        "theme": "The Arrival",
        "target_minutes": 285,
        "description": (
            "Day 1. Starts with coffee-and-breakfast reggae-rock and acoustic "
            "country, builds through cruising mid-tempo into party country and "
            "feel-good rap, and closes with full-volume sing-alongs. The energy "
            "curve of an arrival day: mellow morning, loud by sundown."
        ),
        "songs": [
            # — Phase 1: Coffee & breakfast (mellow) —
            ("Stick Figure", "Above the Storm", "4:20", "Rock"),
            ("Jack Johnson", "Banana Pancakes", "3:11", "Rock"),
            ("Zach Bryan", "Better Days", "3:20", "Country"),
            ("O.A.R.", "I Feel Home", "4:31", "Rock"),
            ("Stick Figure feat. Citizen Cope", "Breathe", "4:12", "Rock"),
            ("Tyler Childers", "Universal Sound", "4:18", "Country"),
            ("Bob Marley & The Wailers", "Three Little Birds", "3:00", "Rock"),
            ("Zach Bryan", "God Speed", "3:56", "Country"),
            ("The Lumineers", "Ho Hey", "2:43", "Rock"),
            ("Dispatch", "The General", "4:20", "Rock"),
            ("Chris Stapleton", "Traveller", "3:44", "Country"),
            ("Jimmy Buffett", "Come Monday", "3:10", "Country"),
            # — Phase 2: Waking up —
            ("Tom Petty", "Wildflowers", "3:11", "Classic Rock"),
            ("O.A.R.", "Shattered (Turn the Car Around)", "3:52", "Rock"),
            ("Sublime", "Badfish", "3:05", "Rock"),
            ("Luke Combs", "Doin' This", "3:01", "Country"),
            ("Fleetwood Mac", "Dreams", "4:14", "Classic Rock"),
            ("Morgan Wallen", "Chasin' You", "3:45", "Country"),
            ("Dirty Heads", "Cabin by the Sea", "3:44", "Rock"),
            ("Eric Church", "Talladega", "4:05", "Country"),
            ("Steve Miller Band", "The Joker", "4:26", "Classic Rock"),
            ("Zach Bryan", "Highway Boys", "2:47", "Country"),
            ("Kings of Leon", "Back Down South", "4:01", "Rock"),
            ("Snoop Dogg feat. Pharrell", "Beautiful", "4:59", "Rap"),
            ("Whiskey Myers", "On the River", "3:53", "Country"),
            # — Phase 3: Cruising, energy rising —
            ("Tom Petty", "Learning to Fly", "4:02", "Classic Rock"),
            ("311", "Amber", "3:28", "Rock"),
            ("Kanye West feat. T-Pain", "Good Life", "3:27", "Rap"),
            ("The Black Keys", "Tighten Up", "3:31", "Rock"),
            ("Riley Green", "There Was This Girl", "3:15", "Country"),
            ("Jay-Z feat. Pharrell", "I Just Wanna Love U (Give It 2 Me)", "3:48", "Rap"),
            ("Sublime", "Doin' Time", "4:12", "Rock"),
            ("Midland", "Drinkin' Problem", "4:00", "Country"),
            ("Red Hot Chili Peppers", "Scar Tissue", "3:36", "Rock"),
            ("Nelly", "Country Grammar (Hot Shit)", "4:47", "Rap"),
            ("Eagles", "Peaceful Easy Feeling", "4:16", "Classic Rock"),
            ("Cody Jinks", "Hippies and Cowboys", "4:33", "Country"),
            ("50 Cent feat. Nate Dogg", "21 Questions", "3:44", "Rap"),
            ("Counting Crows", "Mr. Jones", "4:32", "Rock"),
            ("Turnpike Troubadours", "Gin, Smoke, Lies", "3:03", "Country"),
            # — Phase 4: Midday build —
            ("O.A.R.", "Hey Girl", "3:37", "Rock"),
            ("Eminem", "My Name Is", "4:28", "Rap"),
            ("HARDY feat. Lauren Alaina & Devin Dawson", "One Beer", "3:13", "Country"),
            ("Third Eye Blind", "Never Let You Go", "3:58", "Rock"),
            ("Ludacris", "Rollout (My Business)", "4:33", "Rap"),
            ("Morgan Wallen feat. Florida Georgia Line", "Up Down", "2:54", "Country"),
            ("Ma$e", "Feel So Good", "3:54", "Rap"),
            ("Blink-182", "The Rock Show", "2:52", "Rock"),
            ("Outkast", "Rosa Parks", "5:24", "Rap"),
            ("Creedence Clearwater Revival", "Up Around the Bend", "2:42", "Classic Rock"),
            ("Koe Wetzel", "Something to Talk About", "3:35", "Country"),
            ("Big Tymers", "Still Fly", "4:58", "Rap"),
            ("Brooks & Dunn", "Boot Scootin' Boogie", "3:17", "Country"),
            ("2Pac feat. Digital Underground", "I Get Around", "4:19", "Rap"),
            ("Green Day", "When I Come Around", "2:58", "Rock"),
            ("LL Cool J", "Mama Said Knock You Out", "4:53", "Rap"),
            ("Snoop Dogg", "Who Am I? (What's My Name?)", "4:07", "Rap"),
            ("Jason Aldean", "Hicktown", "3:31", "Country"),
            # — Phase 5: Afternoon ramp —
            ("Eminem", "Berzerk", "3:58", "Rap"),
            ("The Offspring", "Self Esteem", "4:17", "Rock"),
            ("Toby Keith", "Should've Been a Cowboy", "3:29", "Country"),
            ("Ice Cube", "Check Yo Self (Remix)", "3:42", "Rap"),
            ("Pearl Jam", "Corduroy", "4:37", "Rock"),
            ("Chris Janson", "Buy Me a Boat", "2:52", "Country"),
            ("Busta Rhymes feat. P. Diddy & Pharrell", "Pass the Courvoisier, Part II", "3:45", "Rap"),
            ("Nas", "Street Dreams", "4:39", "Rap"),
            ("Kid Rock", "Cowboy", "4:17", "Rock"),
            ("Method Man & Redman", "Da Rockwilder", "2:18", "Rap"),
            # — Phase 6: Everyone singing —
            ("Alabama", "Mountain Music", "4:10", "Country"),
            ("Ja Rule feat. Case", "Livin' It Up", "4:17", "Rap"),
            ("Bon Jovi", "You Give Love a Bad Name", "3:43", "Classic Rock"),
            ("Alan Jackson", "Chattahoochee", "3:57", "Country"),
            ("Journey", "Any Way You Want It", "3:22", "Classic Rock"),
            ("Bryan Adams", "Summer of '69", "3:34", "Classic Rock"),
        ],
    },
    {
        "name": "Ballyowen",
        "theme": "We're Here",
        "target_minutes": 300,
        "description": (
            "Day 2, big golf day. Pure confidence: strutting rock openers, "
            "swagger rap, and party country. Blue skies, good swings, no doubts. "
            "Heavier on rock and country as requested, with rap for the walk to "
            "the first tee."
        ),
        "songs": [
            # — Phase 1: Strut out of the gate —
            ("Tom Petty", "American Girl", "3:34", "Classic Rock"),
            ("Foo Fighters", "Learn to Fly", "3:55", "Rock"),
            ("Luke Combs", "1, 2 Many", "3:04", "Country"),
            ("O.A.R.", "City on Down", "4:44", "Rock"),
            ("Morgan Wallen", "Still Goin Down", "3:39", "Country"),
            ("The Black Crowes", "Hard to Handle", "3:08", "Rock"),
            ("Jay-Z", "Roc Boys (And the Winner Is)...", "4:41", "Rap"),
            ("Eric Church", "How 'Bout You", "3:44", "Country"),
            ("Kings of Leon", "Molly's Chambers", "2:15", "Rock"),
            ("Zach Bryan", "Open the Gate", "2:56", "Country"),
            ("AC/DC", "Shoot to Thrill", "5:17", "Classic Rock"),
            ("Ludacris", "Southern Hospitality", "4:20", "Rap"),
            ("Whiskey Myers", "Ballad of a Southern Man", "4:29", "Country"),
            ("Stick Figure", "Fire on the Horizon", "3:48", "Rock"),
            ("Dierks Bentley", "5-1-5-0", "3:10", "Country"),
            ("50 Cent", "If I Can't", "3:17", "Rap"),
            ("Green Day", "Holiday", "3:52", "Rock"),
            ("Jon Pardi", "Dirt on My Boots", "3:32", "Country"),
            ("The Rolling Stones", "Start Me Up", "3:33", "Classic Rock"),
            ("Nas feat. Puff Daddy", "Hate Me Now", "4:42", "Rap"),
            # — Phase 2: Cruising confidence —
            ("Parker McCollum", "To Be Loved by You", "3:35", "Country"),
            ("Jimmy Eat World", "Sweetness", "3:40", "Rock"),
            ("HARDY", "Rednecker", "3:00", "Country"),
            ("T.I.", "Top Back", "4:23", "Rap"),
            ("The Killers", "Somebody Told Me", "3:17", "Rock"),
            ("Randy Houser", "How Country Feels", "3:29", "Country"),
            ("Beastie Boys", "No Sleep Till Brooklyn", "4:07", "Rap"),
            ("Blink-182", "What's My Age Again?", "2:28", "Rock"),
            ("Morgan Wallen", "Ain't That Some", "3:44", "Country"),
            ("Boston", "Rock and Roll Band", "2:59", "Classic Rock"),
            ("Jay-Z", "U Don't Know", "3:19", "Rap"),
            ("Pecos & the Rooftops", "This Damn Song", "3:36", "Country"),
            ("Sublime", "Wrong Way", "2:16", "Rock"),
            ("Eric Church", "Desperate Man", "3:33", "Country"),
            ("DMX", "What's My Name?", "3:33", "Rap"),
            ("Foo Fighters", "Times Like These", "4:26", "Rock"),
            ("Koe Wetzel", "Good Die Young", "3:37", "Country"),
            ("Outkast", "ATLiens", "3:50", "Rap"),
            ("Tom Petty", "You Wreck Me", "3:22", "Classic Rock"),
            ("Chris Stapleton", "Nobody to Blame", "3:00", "Country"),
            # — Phase 3: Midday swagger —
            ("Third Eye Blind", "Graduate", "3:08", "Rock"),
            ("Nelly feat. St. Lunatics", "Air Force Ones", "5:03", "Rap"),
            ("Riley Green", "Damn Good Day to Leave", "2:56", "Country"),
            ("Lynyrd Skynyrd", "What's Your Name", "3:31", "Classic Rock"),
            ("Kanye West", "Can't Tell Me Nothing", "4:31", "Rap"),
            ("Cage the Elephant", "Ain't No Rest for the Wicked", "2:55", "Rock"),
            ("Luke Combs", "Cold as You", "2:44", "Country"),
            ("Snoop Dogg & Wiz Khalifa feat. Bruno Mars", "Young, Wild & Free", "3:27", "Rap"),
            ("Matchbox Twenty", "Real World", "3:50", "Rock"),
            ("Turnpike Troubadours", "Every Girl", "4:17", "Country"),
            ("Eminem", "Superman", "5:50", "Rap"),
            ("ZZ Top", "Sharp Dressed Man", "4:15", "Classic Rock"),
            ("Zach Bryan", "Quittin' Time", "3:20", "Country"),
            ("50 Cent", "Disco Inferno", "3:35", "Rap"),
            ("Mike Jones feat. Slim Thug & Paul Wall", "Still Tippin'", "4:33", "Rap"),
            ("Brantley Gilbert", "Country Must Be Country Wide", "3:35", "Country"),
            ("Incubus", "Pardon Me", "3:44", "Rock"),
            ("The Game feat. 50 Cent", "How We Do", "3:55", "Rap"),
            ("Hank Williams Jr.", "A Country Boy Can Survive", "4:22", "Country"),
            ("Weezer", "Hash Pipe", "3:06", "Rock"),
            # — Phase 4: Afternoon heaters —
            ("Fabolous feat. Tamia", "Breathe", "3:44", "Rap"),
            ("Travis Tritt", "T-R-O-U-B-L-E", "2:59", "Country"),
            ("Stone Temple Pilots", "Vasoline", "2:56", "Rock"),
            ("Young Jeezy feat. Kanye West", "Put On", "5:20", "Rap"),
            ("Eagles", "Already Gone", "4:13", "Classic Rock"),
            ("Cody Jinks", "Must Be the Whiskey", "3:36", "Country"),
            ("Audioslave", "Show Me How to Live", "4:37", "Rock"),
            ("Rick Ross", "Hustlin'", "3:53", "Rap"),
            ("Toby Keith feat. Willie Nelson", "Beer for My Horses", "3:30", "Country"),
            ("Tim McGraw", "Real Good Man", "3:44", "Country"),
            ("The White Stripes", "Fell in Love with a Girl", "1:50", "Rock"),
            ("Lil Wayne", "Fireman", "4:20", "Rap"),
            ("Led Zeppelin", "Good Times Bad Times", "2:46", "Classic Rock"),
            ("Charlie Daniels Band", "The Devil Went Down to Georgia", "3:34", "Country"),
            ("U2", "Beautiful Day", "4:06", "Rock"),
            # — Phase 5: Big finish —
            ("Alan Jackson", "Good Time", "4:03", "Country"),
            ("Dropkick Murphys", "I'm Shipping Up to Boston", "2:33", "Rock"),
            ("Queen", "Fat Bottomed Girls", "4:16", "Classic Rock"),
            ("Def Leppard", "Pour Some Sugar on Me", "4:25", "Classic Rock"),
            ("Big & Rich", "Save a Horse (Ride a Cowboy)", "3:12", "Country"),
        ],
    },
    {
        "name": "Wild Turkey",
        "theme": "Let's Get Loud",
        "target_minutes": 270,
        "description": (
            "The rowdiest day. Rap-heavy wall-to-wall bangers — Ruff Ryders to "
            "crunk to Shady Records — cut with loud rock and party country so "
            "it never flatlines. Built for trash talk, press bets, and volume."
        ),
        "songs": [
            ("DMX", "Ruff Ryders' Anthem", "3:34", "Rap"),
            ("Lil Jon & The East Side Boyz feat. Ying Yang Twins", "Get Low", "5:34", "Rap"),
            ("Dr. Dre feat. Eminem", "Forgot About Dre", "3:42", "Rap"),
            ("Juvenile feat. Mannie Fresh & Lil Wayne", "Back That Azz Up", "4:25", "Rap"),
            ("50 Cent", "P.I.M.P.", "4:09", "Rap"),
            ("Jay-Z feat. UGK", "Big Pimpin'", "4:44", "Rap"),
            ("Ludacris feat. Mystikal & I-20", "Move Bitch", "4:29", "Rap"),
            ("Outkast", "B.O.B. (Bombs Over Baghdad)", "5:04", "Rap"),
            ("Terror Squad", "Lean Back", "4:07", "Rap"),
            ("Nelly", "Hot in Herre", "3:48", "Rap"),
            ("Snoop Dogg", "Gin and Juice", "3:31", "Rap"),
            ("Kid Rock", "Bawitdaba", "4:26", "Rock"),
            ("Chamillionaire feat. Krayzie Bone", "Ridin'", "5:03", "Rap"),
            ("T.I.", "Bring 'Em Out", "3:34", "Rap"),
            ("Busta Rhymes", "Break Ya Neck", "3:55", "Rap"),
            ("HARDY", "Sold Out", "3:15", "Country"),
            ("Lil Wayne", "A Milli", "3:41", "Rap"),
            ("Three 6 Mafia feat. Young Buck & 8Ball & MJG", "Stay Fly", "4:13", "Rap"),
            ("Kanye West", "POWER", "4:52", "Rap"),
            ("DMX", "Party Up (Up in Here)", "4:32", "Rap"),
            ("Eminem feat. Dr. Dre & 50 Cent", "Crack a Bottle", "4:57", "Rap"),
            ("Ja Rule feat. Fat Joe & Jadakiss", "New York", "4:19", "Rap"),
            ("Blink-182", "Feeling This", "2:53", "Rock"),
            ("Jay-Z", "Show Me What You Got", "4:29", "Rap"),
            ("Nas", "Made You Look", "3:26", "Rap"),
            ("Waka Flocka Flame feat. Roscoe Dash & Wale", "No Hands", "4:23", "Rap"),
            ("Koe Wetzel", "Creeps", "3:26", "Country"),
            ("2Pac", "Hit 'Em Up", "5:13", "Rap"),
            ("Beastie Boys", "(You Gotta) Fight for Your Right (To Party)", "3:28", "Rap"),
            ("Petey Pablo", "Raise Up", "4:19", "Rap"),
            ("Brantley Gilbert", "Bottoms Up", "4:14", "Country"),
            ("50 Cent", "Just a Lil Bit", "3:57", "Rap"),
            ("Young Jeezy feat. Akon", "Soul Survivor", "4:40", "Rap"),
            ("Eminem", "Rap God", "6:03", "Rap"),
            ("Rage Against the Machine", "Killing in the Name", "5:14", "Rock"),
            ("Trick Daddy feat. Twista & Lil Jon", "Let's Go", "4:35", "Rap"),
            ("Lil Durk feat. Morgan Wallen", "Broadway Girls", "3:27", "Rap"),
            ("AC/DC", "T.N.T.", "3:34", "Classic Rock"),
            ("The Notorious B.I.G. feat. Bone Thugs-N-Harmony", "Notorious Thugs", "6:07", "Rap"),
            ("Nelly", "#1", "4:47", "Rap"),
            ("Limp Bizkit", "Rollin' (Air Raid Vehicle)", "3:33", "Rock"),
            ("Lil Wayne", "Go DJ", "4:22", "Rap"),
            ("Usher feat. Lil Jon & Ludacris", "Yeah!", "4:10", "Rap"),
            ("Jason Aldean", "She's Country", "3:29", "Country"),
            ("Kanye West feat. Big Sean, Pusha T & 2 Chainz", "Mercy", "5:29", "Rap"),
            ("Cypress Hill", "Insane in the Brain", "3:28", "Rap"),
            ("Green Day", "American Idiot", "2:54", "Rock"),
            ("T.I.", "What You Know", "4:33", "Rap"),
            ("Lil Scrappy feat. Young Buck", "Money in the Bank", "4:07", "Rap"),
            ("Luke Bryan", "Country Girl (Shake It for Me)", "3:45", "Country"),
            ("DMX", "Where the Hood At", "4:24", "Rap"),
            ("Ludacris feat. Shawnna", "What's Your Fantasy", "4:20", "Rap"),
            ("Foo Fighters", "All My Life", "4:23", "Rock"),
            ("2Pac", "Ambitionz Az a Ridah", "4:39", "Rap"),
            ("Kid Rock", "American Bad Ass", "4:26", "Rock"),
            ("E-40 feat. Keak da Sneak", "Tell Me When to Go", "3:55", "Rap"),
            ("Eric Church", "Smoke a Little Smoke", "3:59", "Country"),
            ("Jay-Z feat. Jermaine Dupri", "Money Ain't a Thang", "4:26", "Rap"),
            ("Ram Jam", "Black Betty", "3:57", "Classic Rock"),
            ("Nappy Roots", "Awnaw", "4:14", "Rap"),
            ("Twista feat. Kanye West & Jamie Foxx", "Slow Jamz", "5:16", "Rap"),
            ("Sublime", "Same in the End", "2:36", "Rock"),
            ("Onyx", "Slam", "3:38", "Rap"),
            ("DJ Khaled feat. T-Pain, Ludacris, Snoop Dogg & Rick Ross", "All I Do Is Win", "3:51", "Rap"),
            ("Guns N' Roses", "Welcome to the Jungle", "4:31", "Classic Rock"),
        ],
    },
    {
        "name": "Crystal Springs",
        "theme": "Prime Time",
        "target_minutes": 285,
        "description": (
            "The peak playlist. Every track is a first-ballot hall-of-famer — "
            "the biggest songs from every genre in the rotation, sequenced so "
            "there is never a reason to touch the skip button."
        ),
        "songs": [
            ("Kings of Leon", "Sex on Fire", "3:23", "Rock"),
            ("Jay-Z", "Izzo (H.O.V.A.)", "4:00", "Rap"),
            ("Luke Combs", "Beer Never Broke My Heart", "3:06", "Country"),
            ("AC/DC", "You Shook Me All Night Long", "3:30", "Classic Rock"),
            ("Eminem", "The Real Slim Shady", "4:44", "Rap"),
            ("Zach Bryan", "Oklahoma Smokeshow", "3:15", "Country"),
            ("The Killers", "When You Were Young", "3:40", "Rock"),
            ("Dr. Dre feat. Snoop Dogg", "Still D.R.E.", "4:30", "Rap"),
            ("Morgan Wallen", "Last Night", "2:43", "Country"),
            ("Lynyrd Skynyrd", "Gimme Three Steps", "4:30", "Classic Rock"),
            ("House of Pain", "Jump Around", "3:37", "Rap"),
            ("Eric Church", "Springsteen", "4:23", "Country"),
            ("Foo Fighters", "The Pretender", "4:29", "Rock"),
            ("Warren G feat. Nate Dogg", "Regulate", "4:08", "Rap"),
            ("Tyler Childers", "Whitehouse Road", "3:47", "Country"),
            ("Guns N' Roses", "Paradise City", "6:46", "Classic Rock"),
            ("Kanye West feat. Jamie Foxx", "Gold Digger", "3:28", "Rap"),
            ("Turnpike Troubadours", "Long Hot Summer Day", "3:35", "Country"),
            ("Lit", "My Own Worst Enemy", "2:49", "Rock"),
            ("Snoop Dogg", "Drop It Like It's Hot", "4:30", "Rap"),
            ("Chris Stapleton", "White Horse", "4:00", "Country"),
            ("Tom Petty and the Heartbreakers", "Mary Jane's Last Dance", "4:33", "Classic Rock"),
            ("Nelly feat. City Spud", "Ride wit Me", "4:52", "Rap"),
            ("Koe Wetzel", "February 28, 2016", "3:47", "Country"),
            ("Blink-182", "All the Small Things", "2:47", "Rock"),
            ("2Pac feat. Dr. Dre", "California Love", "4:44", "Rap"),
            ("Alabama", "Dixieland Delight", "3:53", "Country"),
            ("Van Halen", "Panama", "3:31", "Classic Rock"),
            ("The Notorious B.I.G.", "Big Poppa", "4:13", "Rap"),
            ("HARDY", "Truck Bed", "3:15", "Country"),
            ("Sublime", "What I Got", "2:51", "Rock"),
            ("Kendrick Lamar", "HUMBLE.", "2:57", "Rap"),
            ("Riley Green feat. Ella Langley", "You Look Like You Love Me", "3:03", "Country"),
            ("Beastie Boys", "Sabotage", "2:58", "Rap"),
            ("Eminem", "Without Me", "4:50", "Rap"),
            ("Toby Keith", "As Good as I Once Was", "3:57", "Country"),
            ("Weezer", "Buddy Holly", "2:39", "Rock"),
            ("Outkast", "Ms. Jackson", "4:30", "Rap"),
            ("Garth Brooks", "Callin' Baton Rouge", "2:37", "Country"),
            ("Led Zeppelin", "Black Dog", "4:55", "Classic Rock"),
            ("50 Cent feat. Olivia", "Candy Shop", "3:29", "Rap"),
            ("Whiskey Myers", "Stone", "4:04", "Country"),
            ("Red Hot Chili Peppers", "Can't Stop", "4:29", "Rock"),
            ("Jay-Z", "Dirt Off Your Shoulder", "4:05", "Rap"),
            ("Morgan Wallen", "You Proof", "2:37", "Country"),
            ("Creedence Clearwater Revival", "Fortunate Son", "2:20", "Classic Rock"),
            ("Ice Cube", "It Was a Good Day", "4:20", "Rap"),
            ("Zach Bryan", "Something in the Orange", "3:46", "Country"),
            ("Nirvana", "Smells Like Teen Spirit", "5:01", "Rock"),
            ("UGK feat. Outkast", "Int'l Players Anthem (I Choose You)", "4:12", "Rap"),
            ("Cody Jinks", "Loud and Heavy", "4:33", "Country"),
            ("Queen", "Don't Stop Me Now", "3:29", "Classic Rock"),
            ("T.I. feat. Rihanna", "Live Your Life", "5:38", "Rap"),
            ("Dierks Bentley", "Drunk on a Plane", "4:15", "Country"),
            ("The White Stripes", "Seven Nation Army", "3:52", "Rock"),
            ("The Notorious B.I.G. feat. Mase & Puff Daddy", "Mo Money Mo Problems", "4:17", "Rap"),
            ("Luke Combs", "Hurricane", "3:43", "Country"),
            ("The Rolling Stones", "Honky Tonk Women", "3:03", "Classic Rock"),
            ("Kendrick Lamar", "Not Like Us", "4:34", "Rap"),
            ("Jason Aldean", "Dirt Road Anthem", "3:51", "Country"),
            ("O.A.R.", "Love and Memories", "3:20", "Rock"),
            ("J. Cole", "No Role Modelz", "4:52", "Rap"),
            ("Zach Top", "Sounds Like the Radio", "2:57", "Country"),
            ("Dirty Heads", "Vacation", "3:20", "Rock"),
            ("DMX", "X Gon' Give It to Ya", "3:37", "Rap"),
            ("Eagles", "Life in the Fast Lane", "4:46", "Classic Rock"),
            ("Ludacris", "Stand Up", "3:33", "Rap"),
            ("Stick Figure feat. Slightly Stoopid", "World on Fire", "4:23", "Rock"),
            ("Kid Cudi", "Pursuit of Happiness", "4:55", "Rap"),
            ("Travis Tritt", "It's a Great Day to Be Alive", "4:35", "Country"),
            ("Jimmy Eat World", "The Middle", "2:45", "Rock"),
            ("Kanye West feat. Lupe Fiasco", "Touch the Sky", "3:57", "Rap"),
            ("Outkast", "Hey Ya!", "3:55", "Rap"),
            ("Bon Jovi", "It's My Life", "3:44", "Rock"),
        ],
    },
    {
        "name": "Cascades",
        "theme": "Golden Hour",
        "target_minutes": 150,
        "description": (
            "Late afternoon, drinks flowing, sun getting low. Country comes "
            "back and classic rock takes over — warm, melodic, feel-good "
            "songs for the patio and the last few holes of daylight."
        ),
        "songs": [
            ("Van Morrison", "Into the Mystic", "3:29", "Classic Rock"),
            ("Zach Bryan", "Pink Skies", "3:07", "Country"),
            ("Tom Petty", "Free Fallin'", "4:16", "Classic Rock"),
            ("Kenny Chesney feat. Uncle Kracker", "When the Sun Goes Down", "3:56", "Country"),
            ("The Allman Brothers Band", "Blue Sky", "5:09", "Classic Rock"),
            ("Morgan Wallen", "Sand in My Boots", "3:38", "Country"),
            ("Bob Seger", "Night Moves", "5:25", "Classic Rock"),
            ("Chris Stapleton", "Starting Over", "4:03", "Country"),
            ("Fleetwood Mac", "Everywhere", "3:41", "Classic Rock"),
            ("Eric Church", "Give Me Back My Hometown", "4:03", "Country"),
            ("Eagles", "Tequila Sunrise", "2:52", "Classic Rock"),
            ("Luke Combs", "Fast Car", "4:25", "Country"),
            ("Steve Miller Band", "Fly Like an Eagle", "4:42", "Classic Rock"),
            ("Tyler Childers", "All Your'n", "3:43", "Country"),
            ("Creedence Clearwater Revival", "Have You Ever Seen the Rain", "2:38", "Classic Rock"),
            ("Parker McCollum", "Pretty Heart", "3:05", "Country"),
            ("The Marshall Tucker Band", "Can't You See", "6:01", "Classic Rock"),
            ("Jimmy Buffett", "Margaritaville", "4:11", "Country"),
            ("Lynyrd Skynyrd", "Simple Man", "5:57", "Classic Rock"),
            ("Alan Jackson feat. Jimmy Buffett", "It's Five O'Clock Somewhere", "3:50", "Country"),
            ("The Doobie Brothers", "Black Water", "4:15", "Classic Rock"),
            ("Whiskey Myers", "Broken Window Serenade", "4:47", "Country"),
            ("Bob Seger", "Against the Wind", "5:33", "Classic Rock"),
            ("Zach Bryan", "Burn, Burn, Burn", "4:03", "Country"),
            ("Turnpike Troubadours", "7&7", "3:20", "Country"),
            ("America", "Ventura Highway", "3:32", "Classic Rock"),
            ("Cody Jinks", "Cast No Stones", "4:20", "Country"),
            ("The Band", "The Weight", "4:34", "Classic Rock"),
            ("Jon Pardi", "Head Over Boots", "3:14", "Country"),
            ("Stick Figure", "Golden Hour", "4:34", "Rock"),
            ("Charles Wesley Godwin", "Family Ties", "3:39", "Country"),
            ("Eddie Money", "Take Me Home Tonight", "3:57", "Classic Rock"),
            ("Dire Straits", "Walk of Life", "4:12", "Classic Rock"),
            ("Randy Houser", "Runnin' Outta Moonlight", "3:14", "Country"),
            ("Tom Petty", "You Don't Know How It Feels", "4:47", "Classic Rock"),
            ("Jamey Johnson", "In Color", "5:05", "Country"),
            ("George Strait", "Amarillo by Morning", "2:29", "Country"),
            ("Van Morrison", "Brown Eyed Girl", "3:03", "Classic Rock"),
        ],
    },
    {
        "name": "Black Bear",
        "theme": "Last Dance",
        "target_minutes": 270,
        "description": (
            "Final round. Nostalgia-loaded — the 90s and 2000s songs everyone "
            "grew up on, building to an emotional big finish. Ends with the "
            "song that ends everything."
        ),
        "songs": [
            ("Zach Bryan", "Nine Ball", "3:17", "Country"),
            ("O.A.R.", "Black Rock", "4:16", "Rock"),
            ("Eminem", "Sing for the Moment", "5:40", "Rap"),
            ("Third Eye Blind", "Jumper", "4:33", "Rock"),
            ("Morgan Wallen", "'98 Braves", "3:41", "Country"),
            ("Boston", "More Than a Feeling", "4:45", "Classic Rock"),
            ("Jay-Z", "Hard Knock Life (Ghetto Anthem)", "3:59", "Rap"),
            ("Luke Combs", "She Got the Best of Me", "3:12", "Country"),
            ("Green Day", "Basket Case", "3:01", "Rock"),
            ("Tom Petty", "I Won't Back Down", "2:56", "Classic Rock"),
            ("Nelly", "Just a Dream", "3:58", "Rap"),
            ("Eric Church", "Record Year", "3:45", "Country"),
            ("Oasis", "Wonderwall", "4:18", "Rock"),
            ("Zach Bryan", "Oklahoma City", "4:20", "Country"),
            ("Skee-Lo", "I Wish", "4:08", "Rap"),
            ("Whiskey Myers", "Early Morning Shakes", "4:31", "Country"),
            ("Foo Fighters", "My Hero", "4:20", "Rock"),
            ("2Pac feat. Talent", "Changes", "4:31", "Rap"),
            ("Alan Jackson", "Drive (For Daddy Gene)", "4:02", "Country"),
            ("Matchbox Twenty", "3AM", "3:46", "Rock"),
            ("Fort Minor feat. Styles of Beyond", "Remember the Name", "3:50", "Rap"),
            ("Chris Stapleton", "Broken Halos", "3:03", "Country"),
            ("Counting Crows", "Hanginaround", "4:07", "Rock"),
            ("Ludacris feat. Nate Dogg", "Area Codes", "4:25", "Rap"),
            ("Tim McGraw", "Something Like That", "3:03", "Country"),
            ("The Wallflowers", "One Headlight", "5:14", "Rock"),
            ("Jay-Z feat. Alicia Keys", "Empire State of Mind", "4:36", "Rap"),
            ("Joe Diffie", "Pickup Man", "3:44", "Country"),
            ("Gin Blossoms", "Hey Jealousy", "3:56", "Rock"),
            ("Eminem", "The Way I Am", "4:50", "Rap"),
            ("Hootie & the Blowfish", "Only Wanna Be with You", "3:46", "Rock"),
            ("Zach Top", "I Never Lie", "3:15", "Country"),
            ("Stick Figure feat. Slightly Stoopid", "Choice Is Yours", "3:47", "Rock"),
            ("Nas", "If I Ruled the World (Imagine That)", "4:42", "Rap"),
            ("Flatland Cavalry", "A Life Where We Work Out", "3:59", "Country"),
            ("Nine Days", "Absolutely (Story of a Girl)", "3:09", "Rock"),
            ("Dr. Dre feat. Snoop Dogg", "Nuthin' but a 'G' Thang", "3:58", "Rap"),
            ("Kenny Chesney", "Young", "3:53", "Country"),
            ("Blink-182", "First Date", "2:51", "Rock"),
            ("Coolio feat. L.V.", "Gangsta's Paradise", "4:00", "Rap"),
            ("Brooks & Dunn", "My Maria", "3:48", "Country"),
            ("Vertical Horizon", "Everything You Want", "4:15", "Rock"),
            ("50 Cent", "Wanksta", "3:47", "Rap"),
            ("David Lee Murphy", "Dust on the Bottle", "3:53", "Country"),
            ("Incubus", "Drive", "3:52", "Rock"),
            ("Outkast", "Elevators (Me & You)", "4:24", "Rap"),
            ("George Strait", "Check Yes or No", "3:12", "Country"),
            ("Collective Soul", "Shine", "5:05", "Rock"),
            ("The Notorious B.I.G.", "Juicy", "5:02", "Rap"),
            ("John Michael Montgomery", "Sold (The Grundy County Auction Incident)", "2:52", "Country"),
            ("Red Hot Chili Peppers", "Under the Bridge", "4:24", "Rock"),
            ("Kanye West feat. Chris Martin", "Homecoming", "3:23", "Rap"),
            ("Garth Brooks", "Ain't Goin' Down ('Til the Sun Comes Up)", "4:28", "Country"),
            ("Chingy", "Right Thurr", "4:08", "Rap"),
            ("Ja Rule feat. Ashanti", "Always on Time", "4:05", "Rap"),
            ("Dierks Bentley", "What Was I Thinkin'", "3:45", "Country"),
            ("D12", "My Band", "4:59", "Rap"),
            ("T.I. feat. Justin Timberlake", "Dead and Gone", "4:57", "Rap"),
            ("Alan Jackson", "Where I Come From", "4:07", "Country"),
            # — The big finish —
            ("Bruce Springsteen", "Glory Days", "4:15", "Classic Rock"),
            ("Mark Morrison", "Return of the Mack", "3:32", "Rap"),
            ("Luke Combs", "Even Though I'm Leaving", "3:43", "Country"),
            ("Foo Fighters", "Best of You", "4:15", "Rock"),
            ("Montell Jordan", "This Is How We Do It", "3:59", "Rap"),
            ("Zac Brown Band", "Chicken Fried", "3:58", "Country"),
            ("Pearl Jam", "Alive", "5:41", "Rock"),
            ("John Mellencamp", "Jack & Diane", "4:17", "Classic Rock"),
            ("Green Day", "Good Riddance (Time of Your Life)", "2:34", "Rock"),
        ],
    },
    {
        "name": "Airbnb Morning",
        "theme": "Coffee & Breakfast",
        "target_minutes": 180,
        "description": (
            "Slow starts. Acoustic country, coffee-shop reggae-rock, and warm "
            "folk for eggs, hangovers, and the first cup. Nothing louder than "
            "the griddle until the last few tracks ease the day open."
        ),
        "songs": [
            ("Jack Johnson", "Better Together", "3:27", "Rock"),
            ("Zach Bryan", "Sun to Me", "3:26", "Country"),
            ("Stick Figure", "Once in a Lifetime", "5:22", "Rock"),
            ("Chris Stapleton", "Millionaire", "3:56", "Country"),
            ("Jason Mraz", "I'm Yours", "4:02", "Rock"),
            ("Tyler Childers", "Lady May", "3:03", "Country"),
            ("O.A.R.", "Peace", "3:20", "Rock"),
            ("Ray LaMontagne", "You Are the Best Thing", "3:56", "Rock"),
            ("Zach Bryan feat. The Lumineers", "Spotless", "3:44", "Country"),
            ("Dispatch", "Elias", "3:40", "Rock"),
            ("Willie Nelson", "On the Road Again", "2:38", "Country"),
            ("Jack Johnson", "Upside Down", "3:28", "Rock"),
            ("Charles Wesley Godwin", "All Again", "3:44", "Country"),
            ("Slightly Stoopid", "Closer to the Sun", "3:53", "Rock"),
            ("Luke Combs", "Beautiful Crazy", "3:13", "Country"),
            ("The Lumineers", "Stubborn Love", "4:38", "Rock"),
            ("Sturgill Simpson", "Turtles All the Way Down", "2:56", "Country"),
            ("Bob Marley & The Wailers", "Is This Love", "3:52", "Rock"),
            ("John Mayer", "Waiting on the World to Change", "3:20", "Rock"),
            ("Riley Green", "I Wish Grandpas Never Died", "3:12", "Country"),
            ("Donavon Frankenreiter", "Free", "3:29", "Rock"),
            ("Flatland Cavalry", "War with My Mind", "3:26", "Country"),
            ("Dave Matthews Band", "Satellite", "4:51", "Rock"),
            ("Morgan Wallen", "7 Summers", "3:33", "Country"),
            ("Rebelution", "Safe and Sound", "3:43", "Rock"),
            ("Tyler Childers", "Nose on the Grindstone", "3:36", "Country"),
            ("Ben Harper", "Steal My Kisses", "4:04", "Rock"),
            ("Eric Church", "Like Jesus Does", "3:53", "Country"),
            ("Toad the Wet Sprocket", "Walk on the Ocean", "2:59", "Rock"),
            ("Zac Brown Band", "Toes", "4:22", "Country"),
            ("Michael Franti & Spearhead", "Say Hey (I Love You)", "3:55", "Rock"),
            ("Colter Wall", "Sleeping on the Blacktop", "3:11", "Country"),
            ("Iration", "Time Bomb", "3:37", "Rock"),
            ("Turnpike Troubadours", "The Bird Hunters", "5:05", "Country"),
            ("Dirty Heads", "Oxygen", "3:23", "Rock"),
            ("Brooks & Dunn", "Red Dirt Road", "4:03", "Country"),
            ("Slightly Stoopid", "Collie Man", "3:44", "Rock"),
            ("Kip Moore", "Somethin' 'Bout a Truck", "3:24", "Country"),
            ("Goo Goo Dolls", "Name", "4:30", "Rock"),
            ("Stick Figure", "Way of Life", "4:20", "Rock"),
            ("Tim McGraw", "Where the Green Grass Grows", "3:22", "Country"),
            ("Fleetwood Mac", "Never Going Back Again", "2:14", "Classic Rock"),
            ("The Allman Brothers Band", "Melissa", "3:54", "Classic Rock"),
            ("Mt. Joy", "Silver Lining", "3:37", "Rock"),
            ("Xavier Rudd", "Follow the Sun", "4:10", "Rock"),
            ("Kenny Chesney", "American Kids", "3:26", "Country"),
            ("Eagles", "Seven Bridges Road", "3:01", "Classic Rock"),
            ("Creedence Clearwater Revival", "Lookin' Out My Back Door", "2:33", "Classic Rock"),
        ],
    },
    {
        "name": "Airbnb Evening",
        "theme": "Fire Pit & Cards",
        "target_minutes": 300,
        "description": (
            "The long night: dinner-and-drinks groove, a money-and-cards rap "
            "run for the gambling hours, a rowdy peak, then the fire pit "
            "sing-along run — the songs four guys yell at a fire at 1am."
        ),
        "songs": [
            # — Phase 1: Dinner & drinks groove —
            ("Kenny Chesney", "No Shoes, No Shirt, No Problems", "3:35", "Country"),
            ("Sublime", "Caress Me Down", "3:32", "Rock"),
            ("Jay-Z", "Heart of the City (Ain't No Love)", "3:43", "Rap"),
            ("Eric Church", "Guys Like Me", "3:35", "Country"),
            ("Stick Figure", "Paradise", "4:20", "Rock"),
            ("Santana feat. Rob Thomas", "Smooth", "4:56", "Rock"),
            ("Morgan Wallen", "Wasted on You", "2:58", "Country"),
            ("Q-Tip", "Vivrant Thing", "3:16", "Rap"),
            ("Whiskey Myers", "Deep Down in the South", "3:31", "Country"),
            ("Jimmy Buffett", "Cheeseburger in Paradise", "2:51", "Country"),
            ("O.A.R.", "Night Shift", "4:58", "Rock"),
            ("Nappy Roots", "Good Day", "3:57", "Rap"),
            ("Zac Brown Band feat. Jimmy Buffett", "Knee Deep", "3:12", "Country"),
            ("The Doobie Brothers", "Listen to the Music", "3:48", "Classic Rock"),
            ("J. Cole feat. Miguel", "Power Trip", "4:01", "Rap"),
            ("Dierks Bentley", "Somewhere on a Beach", "3:34", "Country"),
            ("311", "Down", "2:52", "Rock"),
            ("Ludacris feat. Pharrell", "Money Maker", "3:52", "Rap"),
            ("Toby Keith", "Red Solo Cup", "3:38", "Country"),
            # — Phase 2: Cards, money, gambling —
            ("Jay-Z", "99 Problems", "3:54", "Rap"),
            ("Kenny Rogers", "The Gambler", "3:32", "Country"),
            ("Wu-Tang Clan", "C.R.E.A.M.", "4:12", "Rap"),
            ("AC/DC", "Have a Drink on Me", "3:58", "Classic Rock"),
            ("Puff Daddy feat. Ma$e & The Notorious B.I.G.", "It's All About the Benjamins", "4:37", "Rap"),
            ("Chris Stapleton", "Might as Well Get Stoned", "3:22", "Country"),
            ("Steve Miller Band", "Jungle Love", "3:07", "Classic Rock"),
            ("Ol' Dirty Bastard feat. Kelis", "Got Your Money", "4:03", "Rap"),
            ("Koe Wetzel & Jessie Murph", "High Road", "2:59", "Country"),
            ("Beastie Boys", "Intergalactic", "3:50", "Rap"),
            ("ZZ Top", "La Grange", "3:52", "Classic Rock"),
            ("50 Cent", "I Get Money", "3:53", "Rap"),
            ("Luke Combs", "Ain't No Love in Oklahoma", "3:04", "Country"),
            ("Cake", "The Distance", "3:01", "Rock"),
            ("T.I.", "Whatever You Like", "4:07", "Rap"),
            ("Hank Williams Jr.", "All My Rowdy Friends Are Coming Over Tonight", "2:52", "Country"),
            ("The Rolling Stones", "Tumbling Dice", "3:47", "Classic Rock"),
            ("Nelly feat. Paul Wall, Ali & Gipp", "Grillz", "4:30", "Rap"),
            ("Lil Wayne feat. Static Major", "Lollipop", "4:59", "Rap"),
            ("Sublime", "40oz. to Freedom", "3:03", "Rock"),
            ("Ice Cube", "You Can Do It", "4:14", "Rap"),
            ("Garth Brooks", "Two Piña Coladas", "3:44", "Country"),
            # — Phase 3: Rowdy peak —
            ("Steve Earle", "Copperhead Road", "4:30", "Country"),
            ("Afroman", "Because I Got High", "3:17", "Rap"),
            ("Tom Petty", "You Got Lucky", "3:34", "Classic Rock"),
            ("Eminem feat. Nate Dogg", "Shake That", "4:34", "Rap"),
            ("Travis Tritt", "Here's a Quarter (Call Someone Who Cares)", "2:49", "Country"),
            ("Lynyrd Skynyrd", "Call Me the Breeze", "5:09", "Classic Rock"),
            ("Ma$e", "Welcome Back", "3:20", "Rap"),
            ("Zach Bryan feat. The War and Treaty", "Hey Driver", "3:44", "Country"),
            ("The Killers", "All These Things That I've Done", "5:01", "Rock"),
            ("Cam'ron feat. Juelz Santana", "Hey Ma", "3:55", "Rap"),
            ("Jason Aldean", "My Kinda Party", "4:11", "Country"),
            ("Bob Seger", "Old Time Rock and Roll", "3:13", "Classic Rock"),
            ("Outkast", "The Way You Move", "3:54", "Rap"),
            ("Pearl Jam", "Last Kiss", "3:16", "Rock"),
            ("Brooks & Dunn", "Neon Moon", "4:24", "Country"),
            ("The Notorious B.I.G.", "One More Chance (Stay with Me Remix)", "4:42", "Rap"),
            ("Fleetwood Mac", "Go Your Own Way", "3:38", "Classic Rock"),
            ("Uncle Kracker feat. Dobie Gray", "Drift Away", "4:19", "Rock"),
            ("Post Malone feat. Morgan Wallen", "I Had Some Help", "2:58", "Country"),
            ("Smash Mouth", "All Star", "3:20", "Rock"),
            ("Blues Traveler", "Run-Around", "4:39", "Rock"),
            ("Toby Keith", "I Love This Bar", "5:00", "Country"),
            ("Jim Croce", "Bad, Bad Leroy Brown", "3:02", "Classic Rock"),
            ("Barenaked Ladies", "One Week", "2:50", "Rock"),
            # — Phase 4: Fire pit sing-alongs —
            ("David Allan Coe", "You Never Even Called Me by My Name", "5:12", "Country"),
            ("Biz Markie", "Just a Friend", "4:03", "Rap"),
            ("Darius Rucker", "Wagon Wheel", "4:57", "Country"),
            ("Zach Bryan feat. Kacey Musgraves", "I Remember Everything", "3:47", "Country"),
            ("Oasis", "Don't Look Back in Anger", "4:48", "Rock"),
            ("John Denver", "Take Me Home, Country Roads", "3:10", "Country"),
            ("Nathaniel Rateliff & The Night Sweats", "S.O.B.", "4:07", "Rock"),
            ("Billy Joel", "Piano Man", "5:38", "Classic Rock"),
            ("Neil Diamond", "Sweet Caroline", "3:21", "Classic Rock"),
            ("Lynyrd Skynyrd", "Sweet Home Alabama", "4:43", "Classic Rock"),
            ("Bon Jovi", "Livin' on a Prayer", "4:09", "Classic Rock"),
            ("Garth Brooks", "Friends in Low Places", "4:28", "Country"),
        ],
    },
    {
        "name": "Trip Anthem",
        "theme": "The Crystal Springs Golf Trip Soundtrack",
        "target_minutes": 115,
        "description": (
            "The highlight reel. Opens like pulling out of the driveway, peaks "
            "like the trip in full swing, and closes like the drive home with "
            "the windows down. Every song passes the test: 'YES. This song "
            "was made for this trip.'"
        ),
        "songs": [
            # — Act I: Leaving for the trip —
            ("O.A.R.", "This Town", "3:57", "Rock"),
            ("Stick Figure", "Smoke Signals", "5:04", "Rock"),
            ("Zach Bryan", "Heading South", "3:31", "Country"),
            ("Tom Petty and the Heartbreakers", "Runnin' Down a Dream", "4:23", "Classic Rock"),
            ("Steve Miller Band", "Take the Money and Run", "2:50", "Classic Rock"),
            # — Act II: The trip in full swing —
            ("AC/DC", "Thunderstruck", "4:52", "Classic Rock"),
            ("Eminem", "Lose Yourself", "5:26", "Rap"),
            ("Jay-Z", "Public Service Announcement (Interlude)", "2:53", "Rap"),
            ("50 Cent", "In da Club", "3:13", "Rap"),
            ("Dr. Dre feat. Snoop Dogg, Kurupt & Nate Dogg", "The Next Episode", "2:41", "Rap"),
            ("Outkast", "So Fresh, So Clean", "4:00", "Rap"),
            ("The Notorious B.I.G.", "Hypnotize", "3:50", "Rap"),
            ("Eminem feat. Nate Dogg", "'Till I Collapse", "4:57", "Rap"),
            ("Morgan Wallen", "Whiskey Glasses", "3:54", "Country"),
            ("Luke Combs", "When It Rains It Pours", "3:38", "Country"),
            ("Eric Church", "Drink in My Hand", "3:19", "Country"),
            ("Whiskey Myers", "Gasoline", "3:18", "Country"),
            ("Kid Rock", "All Summer Long", "4:56", "Rock"),
            # — Act III: The emotional ending / drive home —
            ("The Killers", "Mr. Brightside", "3:42", "Rock"),
            ("Third Eye Blind", "Semi-Charmed Life", "4:28", "Rock"),
            ("Sublime", "Santeria", "3:03", "Rock"),
            ("Foo Fighters", "Everlong", "4:10", "Rock"),
            ("Chris Stapleton", "Tennessee Whiskey", "4:53", "Country"),
            ("Tyler Childers", "Feathered Indians", "3:35", "Country"),
            ("Zach Bryan", "Revival", "4:03", "Country"),
            ("O.A.R.", "That Was a Crazy Game of Poker", "7:05", "Rock"),
            ("Eagles", "Take It Easy", "3:31", "Classic Rock"),
            ("Journey", "Don't Stop Believin'", "4:10", "Classic Rock"),
            ("Semisonic", "Closing Time", "4:34", "Rock"),
        ],
    },
    {
        "name": "The Ride Up",
        "theme": "Pedal Down",
        "target_minutes": 280,
        "max_artist": 10,  # Eminem-heavy by request (default cap is 3)
        "description": (
            "The drive up. Wall-to-wall amped-up sing-along rap — every "
            "chorus is a group shout and every verse somebody in the car "
            "knows word-for-word. Eminem-heavy on purpose: ten Shady-family "
            "cuts plus five more tracks he guests on. Opens full-send, "
            "detours through the old-school belt-it-out block, and pulls "
            "into the resort on Not Afraid."
        ),
        "songs": [
            # — Phase 1: Pulling out of the driveway (full send) —
            ("Meek Mill", "Dreams and Nightmares", "3:56", "Rap"),
            ("Eminem feat. Juice WRLD", "Godzilla", "3:31", "Rap"),
            ("Jay-Z & Kanye West", "Ni**as in Paris", "3:39", "Rap"),
            ("Eminem", "Business", "4:11", "Rap"),
            ("Wiz Khalifa", "Black and Yellow", "3:37", "Rap"),
            ("Kanye West", "Stronger", "5:12", "Rap"),
            ("50 Cent feat. Eminem & Tony Yayo", "Patiently Waiting", "4:48", "Rap"),
            ("M.O.P.", "Ante Up", "3:56", "Rap"),
            ("Lil Wayne feat. Cory Gunz", "6 Foot 7 Foot", "4:09", "Rap"),
            ("Bad Meets Evil", "Fast Lane", "4:10", "Rap"),
            # — Phase 2: Windows down, everyone rapping —
            ("Macklemore & Ryan Lewis feat. Ray Dalton", "Can't Hold Us", "4:18", "Rap"),
            ("Eminem feat. Rihanna", "The Monster", "4:10", "Rap"),
            ("Flo Rida feat. T-Pain", "Low", "3:50", "Rap"),
            ("J-Kwon", "Tipsy", "4:04", "Rap"),
            ("D12", "Purple Pills", "5:00", "Rap"),
            ("The Game feat. 50 Cent", "Hate It or Love It", "3:26", "Rap"),
            ("Nelly feat. P. Diddy & Murphy Lee", "Shake Ya Tailfeather", "4:53", "Rap"),
            ("Eminem", "Just Lose It", "4:08", "Rap"),
            ("Ludacris", "Get Back", "4:30", "Rap"),
            ("Clipse", "Grindin'", "4:30", "Rap"),
            ("P. Diddy feat. Black Rob & Mark Curry", "Bad Boy for Life", "3:42", "Rap"),
            ("Eminem feat. Dr. Dre", "Guilty Conscience", "3:19", "Rap"),
            ("Cam'ron feat. Juelz Santana", "Oh Boy", "3:34", "Rap"),
            ("50 Cent feat. Justin Timberlake & Timbaland", "Ayo Technology", "4:07", "Rap"),
            ("Akon feat. Eminem", "Smack That", "3:33", "Rap"),
            ("Jim Jones", "We Fly High", "4:01", "Rap"),
            ("G-Unit", "Stunt 101", "4:04", "Rap"),
            # — Phase 3: The nostalgia belt (word-for-word) —
            ("Sir Mix-a-Lot", "Baby Got Back", "4:22", "Rap"),
            ("Vanilla Ice", "Ice Ice Baby", "4:31", "Rap"),
            ("MC Hammer", "U Can't Touch This", "4:17", "Rap"),
            ("Kris Kross", "Jump", "3:16", "Rap"),
            ("Naughty by Nature", "Hip Hop Hooray", "4:26", "Rap"),
            ("Run-DMC", "It's Tricky", "3:03", "Rap"),
            ("Beastie Boys", "Brass Monkey", "2:37", "Rap"),
            ("Rob Base & DJ E-Z Rock", "It Takes Two", "4:57", "Rap"),
            ("Luniz feat. Michael Marshall", "I Got 5 on It", "4:14", "Rap"),
            ("Eminem feat. Dido", "Stan", "6:44", "Rap"),
            ("Xzibit", "X", "3:47", "Rap"),
            ("Fat Joe & Remy Ma feat. French Montana & Infared", "All the Way Up", "3:36", "Rap"),
            ("Rick Ross feat. Styles P", "B.M.F. (Blowin' Money Fast)", "4:15", "Rap"),
            ("Eminem", "Like Toy Soldiers", "4:56", "Rap"),
            ("Asher Roth", "I Love College", "4:01", "Rap"),
            ("Soulja Boy", "Crank That (Soulja Boy)", "3:42", "Rap"),
            ("Macklemore & Ryan Lewis feat. Wanz", "Thrift Shop", "3:55", "Rap"),
            ("Jay-Z feat. Eminem", "Renegade", "5:38", "Rap"),
            # — Phase 4: Modern bangers —
            ("Travis Scott", "SICKO MODE", "5:12", "Rap"),
            ("Post Malone feat. Quavo", "Congratulations", "3:40", "Rap"),
            ("Drake feat. Lil Wayne", "The Motto", "3:01", "Rap"),
            ("Kanye West feat. Rihanna & Kid Cudi", "All of the Lights", "4:59", "Rap"),
            ("Big Sean feat. E-40", "I Don't Fuck with You", "4:44", "Rap"),
            ("Kanye West", "Heartless", "3:31", "Rap"),
            ("Eminem feat. Lil Wayne", "No Love", "5:00", "Rap"),
            ("Kid Cudi", "Day 'N' Nite", "3:42", "Rap"),
            ("Drake", "Started From the Bottom", "2:53", "Rap"),
            ("DJ Khaled feat. Drake, Rick Ross & Lil Wayne", "I'm On One", "4:56", "Rap"),
            ("B.o.B feat. Hayley Williams & Eminem", "Airplanes, Pt. II", "4:20", "Rap"),
            ("Jay-Z feat. Rihanna & Kanye West", "Run This Town", "4:27", "Rap"),
            ("Nelly", "E.I.", "4:47", "Rap"),
            ("Juvenile feat. Soulja Slim", "Slow Motion", "4:10", "Rap"),
            ("Outkast", "Roses", "6:09", "Rap"),
            # — Phase 5: Final ascent & Shady landing —
            ("Linkin Park & Jay-Z", "Numb / Encore", "3:25", "Rap"),
            ("Papa Roach", "Last Resort", "3:20", "Rock"),
            ("Too $hort", "Blow the Whistle", "2:46", "Rap"),
            ("Bad Meets Evil feat. Bruno Mars", "Lighters", "5:04", "Rap"),
            ("Drake feat. Kanye West, Lil Wayne & Eminem", "Forever", "5:57", "Rap"),
            ("Eminem feat. Rihanna", "Love the Way You Lie", "4:23", "Rap"),
            ("Eminem", "Not Afraid", "4:08", "Rap"),
        ],
    },
]
